# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/01_module.submodule.ipynb.

# %% auto 0
__all__ = ['Foo']

# %% ../../nbs/api/01_module.submodule.ipynb 3
class Foo:
    def __init__(self):
        pass 
    
    def bar(self):
        print("bar")


