from daisytuner.normalization.map_compact_form import MapCompactForm
from daisytuner.normalization.map_expanded_form import MapExpandedForm
from daisytuner.normalization.map_inlining import MapInlining
from daisytuner.normalization.maximal_map_fission import MaximalMapFission
from daisytuner.normalization.stride_minimization import StrideMinimization
