# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relay.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brelay.proto\x12\x0f\x45\x64gePiRPC_Relay\"\n\n\x08\x45mptyMsg\".\n\nSuccessMsg\x12\x14\n\x07\x63ontent\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_content\"/\n\x05State\x12\x17\n\nstate_bool\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\r\n\x0b_state_bool2\xe1\x01\n\x0cRelayService\x12\x44\n\nopen_relay\x12\x19.EdgePiRPC_Relay.EmptyMsg\x1a\x1b.EdgePiRPC_Relay.SuccessMsg\x12\x45\n\x0b\x63lose_relay\x12\x19.EdgePiRPC_Relay.EmptyMsg\x1a\x1b.EdgePiRPC_Relay.SuccessMsg\x12\x44\n\x0fget_state_relay\x12\x19.EdgePiRPC_Relay.EmptyMsg\x1a\x16.EdgePiRPC_Relay.StateB\x03\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relay_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_EMPTYMSG']._serialized_start=32
  _globals['_EMPTYMSG']._serialized_end=42
  _globals['_SUCCESSMSG']._serialized_start=44
  _globals['_SUCCESSMSG']._serialized_end=90
  _globals['_STATE']._serialized_start=92
  _globals['_STATE']._serialized_end=139
  _globals['_RELAYSERVICE']._serialized_start=142
  _globals['_RELAYSERVICE']._serialized_end=367
_builder.BuildServices(DESCRIPTOR, 'relay_pb2', _globals)
# @@protoc_insertion_point(module_scope)
