# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='rpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\trpc.proto\x12\x03rpc\"\x90\x01\n\nRpcRequest\x12\x19\n\x0cservice_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bmethod_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rrequest_proto\x18\x03 \x01(\x0cH\x02\x88\x01\x01\x42\x0f\n\r_service_nameB\x0e\n\x0c_method_nameB\x10\n\x0e_request_proto\"\xf1\x01\n\x0bRpcResponse\x12\x19\n\x0cservice_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bmethod_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0eresponse_proto\x18\x03 \x01(\x0cH\x02\x88\x01\x01\x12\x16\n\terror_msg\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\'\n\nerror_code\x18\x05 \x01(\x0e\x32\x0e.rpc.ErrorCodeH\x04\x88\x01\x01\x42\x0f\n\r_service_nameB\x0e\n\x0c_method_nameB\x11\n\x0f_response_protoB\x0c\n\n_error_msgB\r\n\x0b_error_code*v\n\tErrorCode\x12\x14\n\x10\x42\x41\x44_MESSAGE_DATA\x10\x00\x12\x16\n\x12INCOMPLETE_MESSAGE\x10\x01\x12\x15\n\x11SERVICE_NOT_FOUND\x10\x02\x12\x14\n\x10METHOD_NOT_FOUND\x10\x03\x12\x0e\n\nRPC_FAILED\x10\x04\x62\x06proto3'
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='rpc.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BAD_MESSAGE_DATA', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INCOMPLETE_MESSAGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='METHOD_NOT_FOUND', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RPC_FAILED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=409,
  serialized_end=527,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
BAD_MESSAGE_DATA = 0
INCOMPLETE_MESSAGE = 1
SERVICE_NOT_FOUND = 2
METHOD_NOT_FOUND = 3
RPC_FAILED = 4



_RPCREQUEST = _descriptor.Descriptor(
  name='RpcRequest',
  full_name='rpc.RpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='rpc.RpcRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='rpc.RpcRequest.method_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_proto', full_name='rpc.RpcRequest.request_proto', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_service_name', full_name='rpc.RpcRequest._service_name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_method_name', full_name='rpc.RpcRequest._method_name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_request_proto', full_name='rpc.RpcRequest._request_proto',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=19,
  serialized_end=163,
)


_RPCRESPONSE = _descriptor.Descriptor(
  name='RpcResponse',
  full_name='rpc.RpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='rpc.RpcResponse.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='rpc.RpcResponse.method_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_proto', full_name='rpc.RpcResponse.response_proto', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='rpc.RpcResponse.error_msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='rpc.RpcResponse.error_code', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_service_name', full_name='rpc.RpcResponse._service_name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_method_name', full_name='rpc.RpcResponse._method_name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_response_proto', full_name='rpc.RpcResponse._response_proto',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_error_msg', full_name='rpc.RpcResponse._error_msg',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_error_code', full_name='rpc.RpcResponse._error_code',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=166,
  serialized_end=407,
)

_RPCREQUEST.oneofs_by_name['_service_name'].fields.append(
  _RPCREQUEST.fields_by_name['service_name'])
_RPCREQUEST.fields_by_name['service_name'].containing_oneof = _RPCREQUEST.oneofs_by_name['_service_name']
_RPCREQUEST.oneofs_by_name['_method_name'].fields.append(
  _RPCREQUEST.fields_by_name['method_name'])
_RPCREQUEST.fields_by_name['method_name'].containing_oneof = _RPCREQUEST.oneofs_by_name['_method_name']
_RPCREQUEST.oneofs_by_name['_request_proto'].fields.append(
  _RPCREQUEST.fields_by_name['request_proto'])
_RPCREQUEST.fields_by_name['request_proto'].containing_oneof = _RPCREQUEST.oneofs_by_name['_request_proto']
_RPCRESPONSE.fields_by_name['error_code'].enum_type = _ERRORCODE
_RPCRESPONSE.oneofs_by_name['_service_name'].fields.append(
  _RPCRESPONSE.fields_by_name['service_name'])
_RPCRESPONSE.fields_by_name['service_name'].containing_oneof = _RPCRESPONSE.oneofs_by_name['_service_name']
_RPCRESPONSE.oneofs_by_name['_method_name'].fields.append(
  _RPCRESPONSE.fields_by_name['method_name'])
_RPCRESPONSE.fields_by_name['method_name'].containing_oneof = _RPCRESPONSE.oneofs_by_name['_method_name']
_RPCRESPONSE.oneofs_by_name['_response_proto'].fields.append(
  _RPCRESPONSE.fields_by_name['response_proto'])
_RPCRESPONSE.fields_by_name['response_proto'].containing_oneof = _RPCRESPONSE.oneofs_by_name['_response_proto']
_RPCRESPONSE.oneofs_by_name['_error_msg'].fields.append(
  _RPCRESPONSE.fields_by_name['error_msg'])
_RPCRESPONSE.fields_by_name['error_msg'].containing_oneof = _RPCRESPONSE.oneofs_by_name['_error_msg']
_RPCRESPONSE.oneofs_by_name['_error_code'].fields.append(
  _RPCRESPONSE.fields_by_name['error_code'])
_RPCRESPONSE.fields_by_name['error_code'].containing_oneof = _RPCRESPONSE.oneofs_by_name['_error_code']
DESCRIPTOR.message_types_by_name['RpcRequest'] = _RPCREQUEST
DESCRIPTOR.message_types_by_name['RpcResponse'] = _RPCRESPONSE
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RpcRequest = _reflection.GeneratedProtocolMessageType('RpcRequest', (_message.Message,), {
  'DESCRIPTOR' : _RPCREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.RpcRequest)
  })
_sym_db.RegisterMessage(RpcRequest)

RpcResponse = _reflection.GeneratedProtocolMessageType('RpcResponse', (_message.Message,), {
  'DESCRIPTOR' : _RPCRESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.RpcResponse)
  })
_sym_db.RegisterMessage(RpcResponse)


# @@protoc_insertion_point(module_scope)
