from _typeshed import Incomplete
from typing import Any, Dict
from websockets import WebSocketClientProtocol as WebSocketClientProtocol

class NotificationManager:
    ws_url: Incomplete
    algo_session_key: Incomplete
    chat_url: Incomplete
    websocket: Incomplete
    tasks: Incomplete
    def __init__(self, ws_url: str, algo_session_key: str) -> None: ...
    async def connect(self) -> None: ...
    async def run_websocket(self) -> None: ...
    def subscribe(self, topic: str) -> None: ...
    def send_message(self, topic: str, data: Dict[str, Any]) -> None: ...
