
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-25T02:10:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "39b752fefe096212bc7284786436c69d095c217e",
 "version": "1.4.dev2408"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
