# coding: utf-8

"""
    IcoTest Voice

    IcoTest Voice API  # noqa: E501

    The version of the OpenAPI document: 1.0.41
    Contact: shaun.hirst@3adesign.co.uk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import icotest_voice
from icotest_voice.models.controller import Controller  # noqa: E501
from icotest_voice.rest import ApiException

class TestController(unittest.TestCase):
    """Controller unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Controller
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = icotest_voice.models.controller.Controller()  # noqa: E501
        if include_optional :
            return Controller(
                controller_id = '10cda64a-0dce-4663-8b47-6ec1867f9568', 
                controller_type = 'dect', 
                description = 'example controller', 
                location = 'server 1 rack 1', 
                callback_url = 'https://server:port', 
                created = '2021-06-24T14:15:22Z', 
                last_contact = '2021-06-24T14:15:22Z'
            )
        else :
            return Controller(
                controller_id = '10cda64a-0dce-4663-8b47-6ec1867f9568',
                controller_type = 'dect',
        )

    def testController(self):
        """Test Controller"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
