# coding: utf-8

"""
    Spacestudio API documentation

    **1.0.0**: Initial version 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacestudio-satellite-client.api.studies_api import StudiesApi


class TestStudiesApi(unittest.TestCase):
    """StudiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StudiesApi()

    def tearDown(self) -> None:
        pass

    def test_create_computation(self) -> None:
        """Test case for create_computation

        CreateComputation
        """
        pass

    def test_create_study(self) -> None:
        """Test case for create_study

        CreateStudy
        """
        pass

    def test_delete_study(self) -> None:
        """Test case for delete_study

        DeleteStudy
        """
        pass

    def test_get_studies(self) -> None:
        """Test case for get_studies

        GetStudies
        """
        pass

    def test_get_study(self) -> None:
        """Test case for get_study

        GetStudy
        """
        pass

    def test_update_study(self) -> None:
        """Test case for update_study

        UpdateStudy
        """
        pass

    def test_update_study_display_configuration(self) -> None:
        """Test case for update_study_display_configuration

        UpdateStudyDisplayConfiguration
        """
        pass


if __name__ == '__main__':
    unittest.main()
