# Generated by Django 4.1.7 on 2023-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process", models.CharField(max_length=65)),
                ("igem_version", models.CharField(default="0.1.1", max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("e", "Error"), ("w", "Warning"), ("s", "Success")],
                        default="s",
                        max_length=1,
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="LogsCollector",
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="igem_version",
            field=models.CharField(default="0.1.1", max_length=15),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="row_collect",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="row_map",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="row_prepare",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="row_reduce",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="status",
            field=models.CharField(
                choices=[("c", "Current"), ("o", "Overwrite"), ("w", "workprocess")],
                default="w",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="time_collect",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="time_map",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="time_prepare",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wfcontrol",
            name="time_reduce",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="wfcontrol",
            name="source_file_version",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
