# Generated by Django 4.2.3 on 2023-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ge", "0005_alter_wfcontrol_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="igem_version",
            field=models.CharField(default="0.1.4", max_length=15),
        ),
        migrations.AlterField(
            model_name="wfcontrol",
            name="igem_version",
            field=models.CharField(default="0.1.4", max_length=15),
        ),
    ]
