# coding: utf-8

# flake8: noqa
"""
    Spacestudio API documentation

    **1.0.0**: Initial version 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from spacestudio-satellite-client.models.advanced_orbit_parameters import AdvancedOrbitParameters
from spacestudio-satellite-client.models.analytical_study_parameters import AnalyticalStudyParameters
from spacestudio-satellite-client.models.announcement import Announcement
from spacestudio-satellite-client.models.baseline_configuration import BaselineConfiguration
from spacestudio-satellite-client.models.circular_altitude_orbit_parameters import CircularAltitudeOrbitParameters
from spacestudio-satellite-client.models.circular_ground_track_repeated_orbit_parameters import CircularGroundTrackRepeatedOrbitParameters
from spacestudio-satellite-client.models.comparison_item import ComparisonItem
from spacestudio-satellite-client.models.comparison_item1 import ComparisonItem1
from spacestudio-satellite-client.models.computation import Computation
from spacestudio-satellite-client.models.computation_mode import ComputationMode
from spacestudio-satellite-client.models.computation_outputs import ComputationOutputs
from spacestudio-satellite-client.models.computation_status import ComputationStatus
from spacestudio-satellite-client.models.computation_type import ComputationType
from spacestudio-satellite-client.models.context_outputs import ContextOutputs
from spacestudio-satellite-client.models.deorbitation import Deorbitation
from spacestudio-satellite-client.models.display_configuration import DisplayConfiguration
from spacestudio-satellite-client.models.display_configuration_comparison_overview import DisplayConfigurationComparisonOverview
from spacestudio-satellite-client.models.drag_perturbation import DragPerturbation
from spacestudio-satellite-client.models.duplicate_scenario_request import DuplicateScenarioRequest
from spacestudio-satellite-client.models.earth_potential_configuration import EarthPotentialConfiguration
from spacestudio-satellite-client.models.earth_potential_perturbation import EarthPotentialPerturbation
from spacestudio-satellite-client.models.elliptical_ground_track_repeated_eccentricity_orbit_parameters import EllipticalGroundTrackRepeatedEccentricityOrbitParameters
from spacestudio-satellite-client.models.elliptical_perigee_alt_apogee_alt_orbit_parameters import EllipticalPerigeeAltApogeeAltOrbitParameters
from spacestudio-satellite-client.models.elliptical_perigee_alt_eccentricity_orbit_parameters import EllipticalPerigeeAltEccentricityOrbitParameters
from spacestudio-satellite-client.models.elliptical_sma_eccentricity_orbit_parameters import EllipticalSmaEccentricityOrbitParameters
from spacestudio-satellite-client.models.leo_station_keeping import LeoStationKeeping
from spacestudio-satellite-client.models.maneuver import Maneuver
from spacestudio-satellite-client.models.maneuver_timeline_slot import ManeuverTimelineSlot
from spacestudio-satellite-client.models.maneuvering_strategy import ManeuveringStrategy
from spacestudio-satellite-client.models.notification import Notification
from spacestudio-satellite-client.models.notification_content import NotificationContent
from spacestudio-satellite-client.models.numerical_ephemeris import NumericalEphemeris
from spacestudio-satellite-client.models.numerical_outputs_configuration import NumericalOutputsConfiguration
from spacestudio-satellite-client.models.numerical_study_parameters import NumericalStudyParameters
from spacestudio-satellite-client.models.orbit import Orbit
from spacestudio-satellite-client.models.orbit_parameters import OrbitParameters
from spacestudio-satellite-client.models.orbit_phasing import OrbitPhasing
from spacestudio-satellite-client.models.orbit_propagation import OrbitPropagation
from spacestudio-satellite-client.models.orbit_timeline_slot import OrbitTimelineSlot
from spacestudio-satellite-client.models.orbital_transfer import OrbitalTransfer
from spacestudio-satellite-client.models.payload import Payload
from spacestudio-satellite-client.models.perturbation import Perturbation
from spacestudio-satellite-client.models.perturbation_type import PerturbationType
from spacestudio-satellite-client.models.platform import Platform
from spacestudio-satellite-client.models.plot import Plot
from spacestudio-satellite-client.models.propulsion_system import PropulsionSystem
from spacestudio-satellite-client.models.raan_phasing import RaanPhasing
from spacestudio-satellite-client.models.scenario import Scenario
from spacestudio-satellite-client.models.scenario_baseline import ScenarioBaseline
from spacestudio-satellite-client.models.simulation_configuration import SimulationConfiguration
from spacestudio-satellite-client.models.single_satellite_analytical_computation_outputs import SingleSatelliteAnalyticalComputationOutputs
from spacestudio-satellite-client.models.single_satellite_numerical_computation_outputs import SingleSatelliteNumericalComputationOutputs
from spacestudio-satellite-client.models.solar_radiation_pressure_perturbation import SolarRadiationPressurePerturbation
from spacestudio-satellite-client.models.spacecraft_geometry import SpacecraftGeometry
from spacestudio-satellite-client.models.study import Study
from spacestudio-satellite-client.models.study_computation import StudyComputation
from spacestudio-satellite-client.models.study_inputs import StudyInputs
from spacestudio-satellite-client.models.study_parameters import StudyParameters
from spacestudio-satellite-client.models.tab import Tab
from spacestudio-satellite-client.models.third_body_perturbation import ThirdBodyPerturbation
from spacestudio-satellite-client.models.thrust_arcs_position import ThrustArcsPosition
from spacestudio-satellite-client.models.timeline_slot import TimelineSlot
