# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.tasks_api_api import TasksAPIApi


class TestTasksAPIApi(unittest.TestCase):
    """TasksAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksAPIApi()

    def tearDown(self) -> None:
        pass

    def test_get_task_info(self) -> None:
        """Test case for get_task_info

        Retrieve information about any ODM task.
        """
        pass

    def test_publish_all_studies(self) -> None:
        """Test case for publish_all_studies

        Asynchronous task that publishes all pending versions across all studies in the instance.
        """
        pass


if __name__ == '__main__':
    unittest.main()
