# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.patch_operation import PatchOperation

class TestPatchOperation(unittest.TestCase):
    """PatchOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchOperation:
        """Test PatchOperation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchOperation`
        """
        model = PatchOperation()
        if include_optional:
            return PatchOperation(
                op = 'add',
                path = '',
                value = None
            )
        else:
            return PatchOperation(
                op = 'add',
        )
        """

    def testPatchOperation(self):
        """Test PatchOperation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
