# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.data_import_jobs_api import DataImportJobsApi


class TestDataImportJobsApi(unittest.TestCase):
    """DataImportJobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataImportJobsApi()

    def tearDown(self) -> None:
        pass

    def test_start_import_expression(self) -> None:
        """Test case for start_import_expression

        Import any tabular data from TSV or GCT files
        """
        pass

    def test_start_import_flow_cytometry(self) -> None:
        """Test case for start_import_flow_cytometry

        Import flow-cytometry data and metadata from FACS and TSV files
        """
        pass

    def test_start_import_libraries(self) -> None:
        """Test case for start_import_libraries

        Import a group of library metadata objects from a TSV file
        """
        pass

    def test_start_import_preparations(self) -> None:
        """Test case for start_import_preparations

        Import a group of preparation metadata objects from a TSV file
        """
        pass

    def test_start_import_samples(self) -> None:
        """Test case for start_import_samples

        Import a group of sample metadata objects from a TSV file
        """
        pass

    def test_start_import_study(self) -> None:
        """Test case for start_import_study

        Import study metadata from a TSV file
        """
        pass

    def test_start_import_variant(self) -> None:
        """Test case for start_import_variant

        Import variation data and metadata from VCF and TSV files
        """
        pass


if __name__ == '__main__':
    unittest.main()
