# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.group_patch import GroupPatch

class TestGroupPatch(unittest.TestCase):
    """GroupPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupPatch:
        """Test GroupPatch
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupPatch`
        """
        model = GroupPatch()
        if include_optional:
            return GroupPatch(
                operations = [
                    {op=add, path=path, value={}}
                    ],
                schemas = [
                    'urn:ietf:params:scim:api:messages:2.0:PatchOp'
                    ]
            )
        else:
            return GroupPatch(
                operations = [
                    {op=add, path=path, value={}}
                    ],
                schemas = [
                    'urn:ietf:params:scim:api:messages:2.0:PatchOp'
                    ],
        )
        """

    def testGroupPatch(self):
        """Test GroupPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
