# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.create_user201_response import CreateUser201Response

class TestCreateUser201Response(unittest.TestCase):
    """CreateUser201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUser201Response:
        """Test CreateUser201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUser201Response`
        """
        model = CreateUser201Response()
        if include_optional:
            return CreateUser201Response(
                active = True,
                emails = [
                    {type=work, value=value, primary=true}
                    ],
                external_id = '',
                id = '',
                schemas = [
                    'urn:ietf:params:scim:schemas:core:2.0:User'
                    ],
                user_name = '',
                display_name = '',
                meta = odm_api.models.create_user_201_response_all_of_meta.createUser_201_response_allOf_meta(
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    resource_type = 'User', )
            )
        else:
            return CreateUser201Response(
                active = True,
                emails = [
                    {type=work, value=value, primary=true}
                    ],
                display_name = '',
        )
        """

    def testCreateUser201Response(self):
        """Test CreateUser201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
