# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.expression_integration_as_user_api import ExpressionIntegrationAsUserApi


class TestExpressionIntegrationAsUserApi(unittest.TestCase):
    """ExpressionIntegrationAsUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExpressionIntegrationAsUserApi()

    def tearDown(self) -> None:
        pass

    def test_get_expression_by_library_as_user(self) -> None:
        """Test case for get_expression_by_library_as_user

        Retrieve expression run-level data by querying related library ID (accession)
        """
        pass

    def test_get_expression_by_preparation_as_user(self) -> None:
        """Test case for get_expression_by_preparation_as_user

        Retrieve expression run-level data by querying related preparation ID (accession)
        """
        pass

    def test_get_expression_by_sample_as_user(self) -> None:
        """Test case for get_expression_by_sample_as_user

        Retrieve expression run-level data by querying related sample ID (accession)
        """
        pass

    def test_get_expression_groups_by_study_as_user(self) -> None:
        """Test case for get_expression_groups_by_study_as_user

        Retrieve group metadata by querying study ID (accession)
        """
        pass

    def test_get_expression_run_to_library_pairs_as_user(self) -> None:
        """Test case for get_expression_run_to_library_pairs_as_user

        Retrieve run-library pairs by group id. Pagination is based on unique runs, not unique pairs.
        """
        pass

    def test_get_expression_run_to_preparation_pairs_as_user(self) -> None:
        """Test case for get_expression_run_to_preparation_pairs_as_user

        Retrieve run-preparation pairs by group id. Pagination is based on unique runs, not unique pairs.
        """
        pass

    def test_get_expression_run_to_sample_pairs_as_user(self) -> None:
        """Test case for get_expression_run_to_sample_pairs_as_user

        Retrieve run-sample pairs by group id. Pagination is based on unique runs, not unique pairs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
