# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.study_integration_as_user_api import StudyIntegrationAsUserApi


class TestStudyIntegrationAsUserApi(unittest.TestCase):
    """StudyIntegrationAsUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StudyIntegrationAsUserApi()

    def tearDown(self) -> None:
        pass

    def test_get_studies_by_libraries_as_user(self) -> None:
        """Test case for get_studies_by_libraries_as_user

        Retrieve study metadata objects by querying related libraries
        """
        pass

    def test_get_studies_by_preparations_as_user(self) -> None:
        """Test case for get_studies_by_preparations_as_user

        Retrieve study metadata objects by querying related preparations
        """
        pass

    def test_get_studies_by_samples_as_user(self) -> None:
        """Test case for get_studies_by_samples_as_user

        Retrieve study metadata objects by querying related samples
        """
        pass

    def test_get_study_by_sample_as_user(self) -> None:
        """Test case for get_study_by_sample_as_user

        Retrieve study metadata by querying sample ID (accession)
        """
        pass

    def test_search_studies_by_filter_as_user(self) -> None:
        """Test case for search_studies_by_filter_as_user

        Find and retrieve studies via full-text or facet query
        """
        pass


if __name__ == '__main__':
    unittest.main()
