# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.variant_integration_as_user_api import VariantIntegrationAsUserApi


class TestVariantIntegrationAsUserApi(unittest.TestCase):
    """VariantIntegrationAsUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VariantIntegrationAsUserApi()

    def tearDown(self) -> None:
        pass

    def test_get_variant_by_sample_as_user(self) -> None:
        """Test case for get_variant_by_sample_as_user

        Retrieve variant run-level data by querying related sample ID (accession)
        """
        pass

    def test_get_variant_groups_by_study_as_user(self) -> None:
        """Test case for get_variant_groups_by_study_as_user

        Retrieve group metadata by querying study ID (accession)
        """
        pass

    def test_get_variant_run_to_sample_pairs_as_user(self) -> None:
        """Test case for get_variant_run_to_sample_pairs_as_user

        Retrieve run-sample pairs by group id. Pagination is based on unique runs, not unique pairs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
