# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.filter_users_response import FilterUsersResponse

class TestFilterUsersResponse(unittest.TestCase):
    """FilterUsersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilterUsersResponse:
        """Test FilterUsersResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilterUsersResponse`
        """
        model = FilterUsersResponse()
        if include_optional:
            return FilterUsersResponse(
                resources = [
                    null
                    ],
                items_per_page = 56,
                schemas = [
                    'urn:ietf:params:scim:api:messages:2.0:ListResponse'
                    ],
                start_index = 56,
                total_results = 56
            )
        else:
            return FilterUsersResponse(
        )
        """

    def testFilterUsersResponse(self):
        """Test FilterUsersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
