# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.create_user201_response_all_of_meta import CreateUser201ResponseAllOfMeta

class TestCreateUser201ResponseAllOfMeta(unittest.TestCase):
    """CreateUser201ResponseAllOfMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUser201ResponseAllOfMeta:
        """Test CreateUser201ResponseAllOfMeta
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUser201ResponseAllOfMeta`
        """
        model = CreateUser201ResponseAllOfMeta()
        if include_optional:
            return CreateUser201ResponseAllOfMeta(
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                resource_type = 'User'
            )
        else:
            return CreateUser201ResponseAllOfMeta(
        )
        """

    def testCreateUser201ResponseAllOfMeta(self):
        """Test CreateUser201ResponseAllOfMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
