# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.preparation_spo_tas_curator_api import PreparationSPoTAsCuratorApi


class TestPreparationSPoTAsCuratorApi(unittest.TestCase):
    """PreparationSPoTAsCuratorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PreparationSPoTAsCuratorApi()

    def tearDown(self) -> None:
        pass

    def test_add_preparations_as_curator(self) -> None:
        """Test case for add_preparations_as_curator

        Add new preparation object
        """
        pass

    def test_delete_preparation_as_curator(self) -> None:
        """Test case for delete_preparation_as_curator

        Delete a preparation object
        """
        pass

    def test_delete_preparation_group_as_curator(self) -> None:
        """Test case for delete_preparation_group_as_curator

        Delete a preparation group with all related preparation objects
        """
        pass

    def test_get_preparation_as_curator(self) -> None:
        """Test case for get_preparation_as_curator

        Retrieve a single preparation object by ID (accession)
        """
        pass

    def test_get_preparation_by_version_as_curator(self) -> None:
        """Test case for get_preparation_by_version_as_curator

        Retrieve a single preparation object by ID (accession)
        """
        pass

    def test_get_preparation_versions_as_curator(self) -> None:
        """Test case for get_preparation_versions_as_curator

        Retrieve a list of object versions by ID
        """
        pass

    def test_get_preparations_by_group_as_curator(self) -> None:
        """Test case for get_preparations_by_group_as_curator

        Retrieve preparations related to the given group
        """
        pass

    def test_search_preparations_as_curator(self) -> None:
        """Test case for search_preparations_as_curator

        List or search for preparation metadata objects
        """
        pass

    def test_update_preparation_as_curator(self) -> None:
        """Test case for update_preparation_as_curator

        Update a preparation object
        """
        pass


if __name__ == '__main__':
    unittest.main()
