# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.objects_page import ObjectsPage

class TestObjectsPage(unittest.TestCase):
    """ObjectsPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObjectsPage:
        """Test ObjectsPage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObjectsPage`
        """
        model = ObjectsPage()
        if include_optional:
            return ObjectsPage(
                filtered_count = 56,
                page_request = {offset=6, limit=50},
                content = [
                    {owner=owner, summary=[{values=[values, values], key=key}, {values=[values, values], key=key}], hasFacs=true, hasTranscriptomics=true, size=1, fileCreation=fileCreation, name=name, accession=accession, hasGenomic=true}
                    ]
            )
        else:
            return ObjectsPage(
        )
        """

    def testObjectsPage(self):
        """Test ObjectsPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
