# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.metadata_presentation import MetadataPresentation

class TestMetadataPresentation(unittest.TestCase):
    """MetadataPresentation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetadataPresentation:
        """Test MetadataPresentation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetadataPresentation`
        """
        model = MetadataPresentation()
        if include_optional:
            return MetadataPresentation(
                metadata = odm_api.models.metadata_presentation_metadata.MetadataPresentation_metadata(
                    source = '', 
                    name = '', 
                    public = True, 
                    id = '', 
                    content = odm_api.models.content.content(), 
                    data_type = '', 
                    content_map = {
                        'key' : None
                        }, 
                    metadata_content = {
                        'key' : None
                        }, 
                    file_id_associated_with_template = '', ),
                relationships = odm_api.models.data_presentation_relationships.DataPresentation_relationships(
                    sample = '', 
                    cell = '', 
                    library = '', 
                    preparation = '', )
            )
        else:
            return MetadataPresentation(
        )
        """

    def testMetadataPresentation(self):
        """Test MetadataPresentation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
