# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.library_spo_tas_user_api import LibrarySPoTAsUserApi


class TestLibrarySPoTAsUserApi(unittest.TestCase):
    """LibrarySPoTAsUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LibrarySPoTAsUserApi()

    def tearDown(self) -> None:
        pass

    def test_get_libraries_by_group_as_user(self) -> None:
        """Test case for get_libraries_by_group_as_user

        Retrieve libraries related to the given group
        """
        pass

    def test_get_library_as_user(self) -> None:
        """Test case for get_library_as_user

        Retrieve a single library object by ID (accession)
        """
        pass

    def test_get_library_by_version_as_user(self) -> None:
        """Test case for get_library_by_version_as_user

        Retrieve a single library object by ID (accession)
        """
        pass

    def test_get_library_versions_as_user(self) -> None:
        """Test case for get_library_versions_as_user

        Retrieve a list of object versions by ID
        """
        pass

    def test_search_libraries_as_user(self) -> None:
        """Test case for search_libraries_as_user

        List or search for library metadata objects
        """
        pass


if __name__ == '__main__':
    unittest.main()
