# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.metadata_versioning_as_curator_api import MetadataVersioningAsCuratorApi


class TestMetadataVersioningAsCuratorApi(unittest.TestCase):
    """MetadataVersioningAsCuratorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetadataVersioningAsCuratorApi()

    def tearDown(self) -> None:
        pass

    def test_publish_study_by_accession_as_curator(self) -> None:
        """Test case for publish_study_by_accession_as_curator

        Asynchronous task that publishes all pending versions for a single study.
        """
        pass


if __name__ == '__main__':
    unittest.main()
