# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.task_info import TaskInfo

class TestTaskInfo(unittest.TestCase):
    """TaskInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskInfo:
        """Test TaskInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskInfo`
        """
        model = TaskInfo()
        if include_optional:
            return TaskInfo(
                id = '',
                name = '',
                status = 'CREATED',
                application = '',
                started_at = 56,
                ended_at = 56,
                created_by = ''
            )
        else:
            return TaskInfo(
        )
        """

    def testTaskInfo(self):
        """Test TaskInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
