# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.library_integration_as_curator_api import LibraryIntegrationAsCuratorApi


class TestLibraryIntegrationAsCuratorApi(unittest.TestCase):
    """LibraryIntegrationAsCuratorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LibraryIntegrationAsCuratorApi()

    def tearDown(self) -> None:
        pass

    def test_create_library_group_sample_group_link_as_curator(self) -> None:
        """Test case for create_library_group_sample_group_link_as_curator

        Create links between samples and libraries
        """
        pass

    def test_create_library_sample_link_as_curator(self) -> None:
        """Test case for create_library_sample_link_as_curator

        Create a link between a library and a sample
        """
        pass

    def test_delete_library_group_sample_group_link_as_curator(self) -> None:
        """Test case for delete_library_group_sample_group_link_as_curator

        Delete links between samples and libraries related to the specified group
        """
        pass

    def test_delete_library_sample_link_as_curator(self) -> None:
        """Test case for delete_library_sample_link_as_curator

        Delete a link between a library and a sample
        """
        pass

    def test_get_libraries_by_samples_as_curator(self) -> None:
        """Test case for get_libraries_by_samples_as_curator

        Retrieve library metadata by querying related samples
        """
        pass

    def test_get_library_by_sample_as_curator(self) -> None:
        """Test case for get_library_by_sample_as_curator

        Retrieve library metadata by querying related sample ID (accession)
        """
        pass

    def test_get_library_groups_by_study_as_curator(self) -> None:
        """Test case for get_library_groups_by_study_as_curator

        Retrieve group metadata by querying study ID (accession)
        """
        pass

    def test_get_library_links_to_samples_as_curator(self) -> None:
        """Test case for get_library_links_to_samples_as_curator

        Retrieve library-samples pairs by group id. Pagination is based on unique libraries, not unique pairs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
