# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.attribute_validation_summary_attribute_invalid_values_inner import AttributeValidationSummaryAttributeInvalidValuesInner

class TestAttributeValidationSummaryAttributeInvalidValuesInner(unittest.TestCase):
    """AttributeValidationSummaryAttributeInvalidValuesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttributeValidationSummaryAttributeInvalidValuesInner:
        """Test AttributeValidationSummaryAttributeInvalidValuesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttributeValidationSummaryAttributeInvalidValuesInner`
        """
        model = AttributeValidationSummaryAttributeInvalidValuesInner()
        if include_optional:
            return AttributeValidationSummaryAttributeInvalidValuesInner(
                value = None,
                count = 56,
                errors = [
                    {errorType=VALUE_NOT_SET, errorMessage=errorMessage}
                    ]
            )
        else:
            return AttributeValidationSummaryAttributeInvalidValuesInner(
        )
        """

    def testAttributeValidationSummaryAttributeInvalidValuesInner(self):
        """Test AttributeValidationSummaryAttributeInvalidValuesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
