# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.xrefset_queries_api import XrefsetQueriesApi


class TestXrefsetQueriesApi(unittest.TestCase):
    """XrefsetQueriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = XrefsetQueriesApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Import a new xrefset file
        """
        pass

    def test_delete_file(self) -> None:
        """Test case for delete_file

        Delete a xrefset with all related data. Only users who uploaded the xrefset are allowed to delete it.
        """
        pass

    def test_get_details_by_accession(self) -> None:
        """Test case for get_details_by_accession

        Retrieve xrefset details
        """
        pass

    def test_search_entries(self) -> None:
        """Test case for search_entries

        Retrieve a list of entries across all xrefsets for given sourceId and targetId
        """
        pass

    def test_search_entries_within_file(self) -> None:
        """Test case for search_entries_within_file

        Retrieve a list of entries for the given xrefset and given sourceId and targetId
        """
        pass


if __name__ == '__main__':
    unittest.main()
