# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.detached_collection_data_inner import DetachedCollectionDataInner

class TestDetachedCollectionDataInner(unittest.TestCase):
    """DetachedCollectionDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetachedCollectionDataInner:
        """Test DetachedCollectionDataInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetachedCollectionDataInner`
        """
        model = DetachedCollectionDataInner()
        if include_optional:
            return DetachedCollectionDataInner(
                genestackaccession = '',
                detached_object_type = 'SAMPLE_GROUP',
                owner_email = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DetachedCollectionDataInner(
                genestackaccession = '',
                detached_object_type = 'SAMPLE_GROUP',
                owner_email = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testDetachedCollectionDataInner(self):
        """Test DetachedCollectionDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
