# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.expression_spo_tas_user_api import ExpressionSPoTAsUserApi


class TestExpressionSPoTAsUserApi(unittest.TestCase):
    """ExpressionSPoTAsUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExpressionSPoTAsUserApi()

    def tearDown(self) -> None:
        pass

    def test_get_expression_as_user(self) -> None:
        """Test case for get_expression_as_user

        Retrieve a single expression object by ID (accession)
        """
        pass

    def test_get_expression_by_version_as_user(self) -> None:
        """Test case for get_expression_by_version_as_user

        Retrieve a single expression object by ID (accession)
        """
        pass

    def test_get_expression_data_as_user(self) -> None:
        """Test case for get_expression_data_as_user

        Retrieve multiple expression data and metadata objects
        """
        pass

    def test_get_expression_group_as_user(self) -> None:
        """Test case for get_expression_group_as_user

        Retrieve a single group object by ID (accession)
        """
        pass

    def test_get_expression_group_by_run_as_user(self) -> None:
        """Test case for get_expression_group_by_run_as_user

        Retrieve a single group object by run ID (accession)
        """
        pass

    def test_get_expression_versions_as_user(self) -> None:
        """Test case for get_expression_versions_as_user

        Retrieve a list of object versions by ID
        """
        pass

    def test_search_expression_groups_as_user(self) -> None:
        """Test case for search_expression_groups_as_user

        Retrieve groups that match a query
        """
        pass

    def test_search_expression_runs_as_user(self) -> None:
        """Test case for search_expression_runs_as_user

        Retrieve run objects related to the given group
        """
        pass


if __name__ == '__main__':
    unittest.main()
