# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.omics_queries_as_user_api import OmicsQueriesAsUserApi


class TestOmicsQueriesAsUserApi(unittest.TestCase):
    """OmicsQueriesAsUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OmicsQueriesAsUserApi()

    def tearDown(self) -> None:
        pass

    def test_omics_search_expression_data_as_user(self) -> None:
        """Test case for omics_search_expression_data_as_user

        Retrieve data objects by searching across multiple data types
        """
        pass

    def test_omics_search_expression_groups_as_user(self) -> None:
        """Test case for omics_search_expression_groups_as_user

        Retrieve group objects by searching across multiple data types
        """
        pass

    def test_omics_search_flow_cytometry_data_as_user(self) -> None:
        """Test case for omics_search_flow_cytometry_data_as_user

        Retrieve flow cytometry data objects by searching across multiple data types
        """
        pass

    def test_omics_search_flow_cytometry_groups_as_user(self) -> None:
        """Test case for omics_search_flow_cytometry_groups_as_user

        Retrieve group objects by searching across multiple data types
        """
        pass

    def test_omics_search_samples_as_user(self) -> None:
        """Test case for omics_search_samples_as_user

        Retrieve sample metadata objects by searching across multiple data types
        """
        pass

    def test_omics_search_streamed_expression_data_as_user(self) -> None:
        """Test case for omics_search_streamed_expression_data_as_user

        Stream data from a given tabular file
        """
        pass

    def test_omics_search_variant_data_as_user(self) -> None:
        """Test case for omics_search_variant_data_as_user

        Retrieve variant data objects by searching across multiple data types
        """
        pass

    def test_omics_search_variant_groups_as_user(self) -> None:
        """Test case for omics_search_variant_groups_as_user

        Retrieve group objects by searching across multiple data types
        """
        pass


if __name__ == '__main__':
    unittest.main()
