# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.study_validation_summary import StudyValidationSummary

class TestStudyValidationSummary(unittest.TestCase):
    """StudyValidationSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StudyValidationSummary:
        """Test StudyValidationSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudyValidationSummary`
        """
        model = StudyValidationSummary()
        if include_optional:
            return StudyValidationSummary(
                samples = [
                    {groupAccession=groupAccession, attributes=[{attributeName=attributeName, attributeInvalidValues=[{count=0, value={}, errors=[{errorType=VALUE_NOT_SET, errorMessage=errorMessage}, {errorType=VALUE_NOT_SET, errorMessage=errorMessage}]}, {count=0, value={}, errors=[{errorType=VALUE_NOT_SET, errorMessage=errorMessage}, {errorType=VALUE_NOT_SET, errorMessage=errorMessage}]}]}, {attributeName=attributeName, attributeInvalidValues=[{count=0, value={}, errors=[{errorType=VALUE_NOT_SET, errorMessage=errorMessage}, {errorType=VALUE_NOT_SET, errorMessage=errorMessage}]}, {count=0, value={}, errors=[{errorType=VALUE_NOT_SET, errorMessage=errorMessage}, {errorType=VALUE_NOT_SET, errorMessage=errorMessage}]}]}]}
                    ]
            )
        else:
            return StudyValidationSummary(
        )
        """

    def testStudyValidationSummary(self):
        """Test StudyValidationSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
