# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.relationships import Relationships

class TestRelationships(unittest.TestCase):
    """Relationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Relationships:
        """Test Relationships
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Relationships`
        """
        model = Relationships()
        if include_optional:
            return Relationships(
                sample = '',
                cell = '',
                library = '',
                preparation = ''
            )
        else:
            return Relationships(
        )
        """

    def testRelationships(self):
        """Test Relationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
