# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.flow_cytometry_item import FlowCytometryItem

class TestFlowCytometryItem(unittest.TestCase):
    """FlowCytometryItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlowCytometryItem:
        """Test FlowCytometryItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlowCytometryItem`
        """
        model = FlowCytometryItem()
        if include_optional:
            return FlowCytometryItem(
                item_id = '',
                metadata = None,
                run_id = '',
                group_id = '',
                readout_type = '',
                cell_population = '',
                marker = '',
                expression = 1.337
            )
        else:
            return FlowCytometryItem(
        )
        """

    def testFlowCytometryItem(self):
        """Test FlowCytometryItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
