# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.create_group201_response import CreateGroup201Response

class TestCreateGroup201Response(unittest.TestCase):
    """CreateGroup201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateGroup201Response:
        """Test CreateGroup201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateGroup201Response`
        """
        model = CreateGroup201Response()
        if include_optional:
            return CreateGroup201Response(
                external_id = '',
                id = '',
                schemas = [
                    'urn:ietf:params:scim:schemas:core:2.0:Group'
                    ],
                members = [
                    {display=display, value=value, $ref=https://openapi-generator.tech}
                    ],
                display_name = '',
                meta = odm_api.models.create_user_201_response_all_of_meta.createUser_201_response_allOf_meta(
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    resource_type = 'User', )
            )
        else:
            return CreateGroup201Response(
                display_name = '',
        )
        """

    def testCreateGroup201Response(self):
        """Test CreateGroup201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
