# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.import_signal_run_request import ImportSignalRunRequest

class TestImportSignalRunRequest(unittest.TestCase):
    """ImportSignalRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportSignalRunRequest:
        """Test ImportSignalRunRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportSignalRunRequest`
        """
        model = ImportSignalRunRequest()
        if include_optional:
            return ImportSignalRunRequest(
                source = 'HTTP',
                metadata_link = 'https://mybucket.s3.amazonaws.com/my-experiment/my-omics-metadata.tsv',
                data_link = 'https://mybucket.s3.amazonaws.com/my-experiment/my-omics-data.gz',
                template_id = 'GSF334953',
                previous_version = 'GSF334953'
            )
        else:
            return ImportSignalRunRequest(
                data_link = 'https://mybucket.s3.amazonaws.com/my-experiment/my-omics-data.gz',
        )
        """

    def testImportSignalRunRequest(self):
        """Test ImportSignalRunRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
