# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.find_objects_response_filter_option_groups_inner import FindObjectsResponseFilterOptionGroupsInner

class TestFindObjectsResponseFilterOptionGroupsInner(unittest.TestCase):
    """FindObjectsResponseFilterOptionGroupsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindObjectsResponseFilterOptionGroupsInner:
        """Test FindObjectsResponseFilterOptionGroupsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindObjectsResponseFilterOptionGroupsInner`
        """
        model = FindObjectsResponseFilterOptionGroupsInner()
        if include_optional:
            return FindObjectsResponseFilterOptionGroupsInner(
                filter_id = '',
                has_more_options = True,
                options = [
                    {filterId=filterId, name=name, count=5, id=id}
                    ]
            )
        else:
            return FindObjectsResponseFilterOptionGroupsInner(
        )
        """

    def testFindObjectsResponseFilterOptionGroupsInner(self):
        """Test FindObjectsResponseFilterOptionGroupsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
