# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.api.validation_summary_as_curator_api import ValidationSummaryAsCuratorApi


class TestValidationSummaryAsCuratorApi(unittest.TestCase):
    """ValidationSummaryAsCuratorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidationSummaryAsCuratorApi()

    def tearDown(self) -> None:
        pass

    def test_search_expression_data_as_curator(self) -> None:
        """Test case for search_expression_data_as_curator

        Retrieve validation summary by querying study ID (accession)
        """
        pass


if __name__ == '__main__':
    unittest.main()
