# coding: utf-8

"""
    Tasks API

    These API endpoints serve to work with asynchronous tasks. 

    The version of the OpenAPI document: default-released
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odm_api.models.variant_signal_source import VariantSignalSource

class TestVariantSignalSource(unittest.TestCase):
    """VariantSignalSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantSignalSource:
        """Test VariantSignalSource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantSignalSource`
        """
        model = VariantSignalSource()
        if include_optional:
            return VariantSignalSource(
                template_id = 'GSF000001',
                link = '',
                metadata_link = '',
                previous_version = ''
            )
        else:
            return VariantSignalSource(
                link = '',
        )
        """

    def testVariantSignalSource(self):
        """Test VariantSignalSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
