# Generated by Django 5.0.2 on 2024-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_infobip", "0002_infobipsms"),
    ]

    operations = [
        migrations.AddField(
            model_name="infobipsms",
            name="response",
            field=models.JSONField(
                blank=True,
                help_text="Infobip response",
                null=True,
                verbose_name="Response",
            ),
        ),
    ]
