
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-22T02:54:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "688bc40ef5867bb299f4de66ea2c03b2300df2c8",
 "version": "1.1.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
