
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-21T18:20:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd6c4fc989f3235a4002fed702011f1e1048b98a",
 "version": "0.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
