
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-25T16:26:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c20226cb117d96e94700863a1bb16084232d214",
 "version": "1.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
