# 常量定义

# 系统目录
BACK_INITIALIZE_DIR_NAME = "initialize"
PASSWORD_FILE_NAME = "__password__"
PASSWORD_DEFAULT = "admin"
SN_ID = "session_id"

# 实例
ROOT_DIR_NAME = "root"
PROJECTS_DIR_NAME = "projects"
APPLICATIONS_DIR_NAME = "applications"
MODULES_DIR_NAME = "modules"

DEFAULT_PROJECT_NAME = "default"
DEFAULT_APPLICATION_NAME = "default"
DEFAULT_MODULE_NAME = "default"

INSTANCE_INDEX_FILE_NAME = "index.py"
INSTANCE_RUN_HTTP_FILE_NAME = "run_http.py"

SETTINGS_FILE_NAME = "__settings__.py"
SETTINGS_DICT_NAME = "settings"

CONFIGS_FILE_NAME = "__configs__.py"
CONFIGS_DICT_NAME = "configs"
TRANSLATIONS_DIR_NAME = "translations"
TRANSLATIONS_DICT_NAME = "translations"

# 设置名称
CN_LANGUAGE = "LANGUAGE"

CN_MYSQL_HOST = "mysql_host"
CN_MYSQL_PORT = "mysql_port"
CN_MYSQL_NAME = "mysql_name"
CN_MYSQL_USER = "mysql_user"
CN_MYSQL_PASS = "mysql_pass"
CN_MYSQL_PREX = "mysql_prefix"

CN_UN_LANGUAGE = "UN_LANGUAGE"

CN_UN_TARGET = "UN_TARGET"
CN_UN_ARGUMENTS = "UN_ARGUMENTS"
CN_UN_METHOD = "UN_METHOD"
CN_UN_SEARCH = "SEARCH"
CN_UN_SEARCH_KEYWORD = "SEARCH_KEYWORD"
CN_UN_SEARCH_PAGE = "SEARCH_PAGE"
CN_UN_SEARCH_ORDERS = "SEARCH_ORDERS"
CN_UN_SEARCH_FILTERS = "SEARCH_FILTERS"
CN_UN_SEARCH_ITEMS_PER_PAGE = "SEARCH_ITEMS_PER_PAGE"
CN_UN_SEARCH_PAGES_PER_GROUP = "SEARCH_PAGES_PER_GROUP"
