# coding: utf-8

"""
    IcoTest Voice

    IcoTest Voice API  # noqa: E501

    The version of the OpenAPI document: 1.0.41
    Contact: shaun.hirst@3adesign.co.uk
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from icotest_voice.configuration import Configuration


class InlineObject2(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'certificates_zip_file': 'file'
    }

    attribute_map = {
        'certificates_zip_file': 'certificates_zip_file'
    }

    def __init__(self, certificates_zip_file=None, local_vars_configuration=None):  # noqa: E501
        """InlineObject2 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._certificates_zip_file = None
        self.discriminator = None

        self.certificates_zip_file = certificates_zip_file

    @property
    def certificates_zip_file(self):
        """Gets the certificates_zip_file of this InlineObject2.  # noqa: E501


        :return: The certificates_zip_file of this InlineObject2.  # noqa: E501
        :rtype: file
        """
        return self._certificates_zip_file

    @certificates_zip_file.setter
    def certificates_zip_file(self, certificates_zip_file):
        """Sets the certificates_zip_file of this InlineObject2.


        :param certificates_zip_file: The certificates_zip_file of this InlineObject2.  # noqa: E501
        :type: file
        """
        if self.local_vars_configuration.client_side_validation and certificates_zip_file is None:  # noqa: E501
            raise ValueError("Invalid value for `certificates_zip_file`, must not be `None`")  # noqa: E501

        self._certificates_zip_file = certificates_zip_file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject2):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineObject2):
            return True

        return self.to_dict() != other.to_dict()
