
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-23T19:11:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bdb381f9e05d3b66b0a6500754f2df033d204db",
 "version": "2024.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
