
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-24T16:23:51+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "c813396e7f7517b4f091699495d91fcdc59a6dd7",
 "version": "0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
