from enum import Enum


class MetricAggregateQueryResourceObjectAttributesSort(str, Enum):
    BOUNCE_TYPE = "Bounce Type"
    CAMPAIGN_NAME = "Campaign Name"
    CLIENT_CANONICAL = "Client Canonical"
    CLIENT_NAME = "Client Name"
    CLIENT_TYPE = "Client Type"
    COUNT = "count"
    EMAIL_DOMAIN = "Email Domain"
    FAILURE_SOURCE = "Failure Source"
    FAILURE_TYPE = "Failure Type"
    FORM_ID = "form_id"
    FROM_NUMBER = "From Number"
    FROM_PHONE_REGION = "From Phone Region"
    LIST = "List"
    MESSAGE_NAME = "Message Name"
    MESSAGE_TYPE = "Message Type"
    METHOD = "Method"
    SUBJECT = "Subject"
    SUM_VALUE = "sum_value"
    TO_NUMBER = "To Number"
    TO_PHONE_REGION = "To Phone Region"
    UNIQUE = "unique"
    URL = "URL"
    VALUE_0 = "$attributed_channel"
    VALUE_1 = "-$attributed_channel"
    VALUE_10 = "$flow"
    VALUE_11 = "-$flow"
    VALUE_12 = "$flow_channel"
    VALUE_13 = "-$flow_channel"
    VALUE_14 = "$message"
    VALUE_15 = "-$message"
    VALUE_16 = "$message_send_cohort"
    VALUE_17 = "-$message_send_cohort"
    VALUE_18 = "$variation"
    VALUE_19 = "-$variation"
    VALUE_2 = "$attributed_flow"
    VALUE_20 = "$variation_send_cohort"
    VALUE_21 = "-$variation_send_cohort"
    VALUE_23 = "-Bounce Type"
    VALUE_25 = "-Campaign Name"
    VALUE_27 = "-Client Canonical"
    VALUE_29 = "-Client Name"
    VALUE_3 = "-$attributed_flow"
    VALUE_31 = "-Client Type"
    VALUE_33 = "-Email Domain"
    VALUE_35 = "-Failure Source"
    VALUE_37 = "-Failure Type"
    VALUE_39 = "-From Number"
    VALUE_4 = "$attributed_message"
    VALUE_41 = "-From Phone Region"
    VALUE_43 = "-List"
    VALUE_45 = "-Message Name"
    VALUE_47 = "-Message Type"
    VALUE_49 = "-Method"
    VALUE_5 = "-$attributed_message"
    VALUE_51 = "-Subject"
    VALUE_53 = "-To Number"
    VALUE_55 = "-To Phone Region"
    VALUE_57 = "-URL"
    VALUE_59 = "-count"
    VALUE_6 = "$attributed_variation"
    VALUE_61 = "-form_id"
    VALUE_63 = "-sum_value"
    VALUE_65 = "-unique"
    VALUE_7 = "-$attributed_variation"
    VALUE_8 = "$campaign_channel"
    VALUE_9 = "-$campaign_channel"

    def __str__(self) -> str:
        return str(self.value)
