VERSION_YEAR = 2024
VERSION_MONTH = int('02')
VERSION_DAY = int('24')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('49')
MAJOR_VERSION = 0
MINOR_VERSION = 13
PATCH_VERSION = 202402241049
version_date = '2024/02/24 10:49'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
