# Generated by Django 4.2.1 on 2023-05-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ge", "0002_logs_delete_logscollector_wfcontrol_igem_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="igem_version",
            field=models.CharField(default="0.1.2", max_length=15),
        ),
        migrations.AlterField(
            model_name="wfcontrol",
            name="igem_version",
            field=models.CharField(default="0.1.2", max_length=15),
        ),
    ]
