# Generated by Django 4.2.1 on 2023-05-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ge", "0004_alter_logs_igem_version_alter_wfcontrol_igem_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wfcontrol",
            name="status",
            field=models.CharField(
                choices=[("c", "Current"), ("o", "Overwrite"), ("w", "WorkProcess")],
                default="w",
                max_length=1,
            ),
        ),
    ]
