
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-24T21:29:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3e05c1cdc840b2d7ab1f73f1093977d6d3639e8",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
