# Generated by Django 4.2.6 on 2024-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_jet_sidebar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_cs',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_cs_sk',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_en',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_pl',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_ro',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_ru',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_ru_md',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_ru_uz',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_sk',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AddField(
            model_name='sidebaritemconfig',
            name='app_custom_name_uk',
            field=models.CharField(blank=True, help_text='Custom name for the app. If not provided, the app name will be used.', max_length=255, null=True, verbose_name='App custom name'),
        ),
        migrations.AlterField(
            model_name='sidebaritemconfig',
            name='app',
            field=models.CharField(choices=[], help_text='Select app for which the sidebar will be displayed', max_length=255, null=True, verbose_name='Apps'),
        ),
        migrations.AlterField(
            model_name='sidebaritemconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
