VERSION_YEAR = 2024
VERSION_MONTH = int('02')
VERSION_DAY = int('26')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('47')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202402260647
version_date = '2024/02/26 06:47'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
