
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-21T20:39:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad1ae5db07d4dd006cdfc992189222481e630c24",
 "version": "1.21.1.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
