
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-24T02:45:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f1e0065d4016e2e3def63cbc7f5dcdd6f229d86",
 "version": "1.3.8rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
