
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-21T12:04:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "171ee69400ba00e1f6fe455a46e1b0a812206bfa",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
