
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-26T11:15:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b26d92e89e59ef2a4a908cbc64ecd35fcbeee47",
 "version": "1.8.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
