# coding: utf-8

"""
    Tickforge API

    An API to interact with Uptick Internal Resources

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Cluster(str, Enum):
    """
    Name of our EKS Clusters
    """

    """
    allowed enum values
    """
    LUNA = 'luna'
    BLUE = 'blue'
    SOOTY = 'sooty'
    THEO = 'theo'
    STAGING = 'staging'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Cluster from a JSON string"""
        return cls(json.loads(json_str))


