# coding: utf-8

"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from fuse_client import schemas  # noqa: F401


class TransactionEventType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Type of the transaction, ie loan
    """


    class MetaOapg:
        enum_value_to_name = {
            "ach": "ACH",
            "adjustment": "ADJUSTMENT",
            "atm": "ATM",
            "bank_charge": "BANK_CHARGE",
            "bill_payment": "BILL_PAYMENT",
            "card_payment": "CARD_PAYMENT",
            "cash": "CASH",
            "cashback": "CASHBACK",
            "charge": "CHARGE",
            "cheque": "CHEQUE",
            "credit": "CREDIT",
            "debit": "DEBIT",
            "deposit": "DEPOSIT",
            "digital_payment": "DIGITAL_PAYMENT",
            "direct_debit": "DIRECT_DEBIT",
            "fee": "FEE",
            "in_store": "IN_STORE",
            "interest": "INTEREST",
            "online": "ONLINE",
            "other": "OTHER",
            "payment": "PAYMENT",
            "purchase": "PURCHASE",
            "standing_order": "STANDING_ORDER",
            "transaction": "TRANSACTION",
            "transfer": "TRANSFER",
            "wire": "WIRE",
            "withdrawal": "WITHDRAWAL",
        }
    
    @schemas.classproperty
    def ACH(cls):
        return cls("ach")
    
    @schemas.classproperty
    def ADJUSTMENT(cls):
        return cls("adjustment")
    
    @schemas.classproperty
    def ATM(cls):
        return cls("atm")
    
    @schemas.classproperty
    def BANK_CHARGE(cls):
        return cls("bank_charge")
    
    @schemas.classproperty
    def BILL_PAYMENT(cls):
        return cls("bill_payment")
    
    @schemas.classproperty
    def CARD_PAYMENT(cls):
        return cls("card_payment")
    
    @schemas.classproperty
    def CASH(cls):
        return cls("cash")
    
    @schemas.classproperty
    def CASHBACK(cls):
        return cls("cashback")
    
    @schemas.classproperty
    def CHARGE(cls):
        return cls("charge")
    
    @schemas.classproperty
    def CHEQUE(cls):
        return cls("cheque")
    
    @schemas.classproperty
    def CREDIT(cls):
        return cls("credit")
    
    @schemas.classproperty
    def DEBIT(cls):
        return cls("debit")
    
    @schemas.classproperty
    def DEPOSIT(cls):
        return cls("deposit")
    
    @schemas.classproperty
    def DIGITAL_PAYMENT(cls):
        return cls("digital_payment")
    
    @schemas.classproperty
    def DIRECT_DEBIT(cls):
        return cls("direct_debit")
    
    @schemas.classproperty
    def FEE(cls):
        return cls("fee")
    
    @schemas.classproperty
    def IN_STORE(cls):
        return cls("in_store")
    
    @schemas.classproperty
    def INTEREST(cls):
        return cls("interest")
    
    @schemas.classproperty
    def ONLINE(cls):
        return cls("online")
    
    @schemas.classproperty
    def OTHER(cls):
        return cls("other")
    
    @schemas.classproperty
    def PAYMENT(cls):
        return cls("payment")
    
    @schemas.classproperty
    def PURCHASE(cls):
        return cls("purchase")
    
    @schemas.classproperty
    def STANDING_ORDER(cls):
        return cls("standing_order")
    
    @schemas.classproperty
    def TRANSACTION(cls):
        return cls("transaction")
    
    @schemas.classproperty
    def TRANSFER(cls):
        return cls("transfer")
    
    @schemas.classproperty
    def WIRE(cls):
        return cls("wire")
    
    @schemas.classproperty
    def WITHDRAWAL(cls):
        return cls("withdrawal")
