VERSION_YEAR = 2024
VERSION_MONTH = int('02')
VERSION_DAY = int('25')
VERSION_HOUR = int('00')
VERSION_MINUTE = int('56')
MAJOR_VERSION = 0
MINOR_VERSION = 1
PATCH_VERSION = 202402250056
version_date = '2024/02/25 00:56'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
