VERSION_YEAR = 2024
VERSION_MONTH = int('02')
VERSION_DAY = int('24')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('09')
MAJOR_VERSION = 0
MINOR_VERSION = 0
PATCH_VERSION = 202402240709
version_date = '2024/02/24 07:09'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
