
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-26T16:52:40+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "54474a1a45bb6c7a22dfd36e84e05eead31d65da",
 "version": "0.3.5.post0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
