__url__ = "https://citros.io"
__title__ = "citros"
__author__ = "lulav"
__license__ = "LICENSE"
__version__ = "0.2.64"
__copyright__ = "Copyright 2024 Lulav Space"
__description__ = "citros"
__author_email__ = "contact@lulav.space"
