from ....libraries.html_document.tags.a import a
from ....libraries.html_document.tags.body import body
from ....libraries.html_document.tags.div import div
from ....libraries.html_document.tags.h1 import h1
from ....libraries.html_document.tags.h2 import h2
from ....libraries.html_document.tags.h3 import h3
from ....libraries.html_document.tags.h4 import h4
from ....libraries.html_document.tags.h5 import h5
from ....libraries.html_document.tags.h6 import h6
from ....libraries.html_document.tags.head import head
from ....libraries.html_document.tags.html import html
from ....libraries.html_document.tags.input_text import input_text
from ....libraries.html_document.tags.link import link
from ....libraries.html_document.tags.script import script
from ....libraries.html_document.tags.span import span
from ....libraries.html_document.tags.table import table
from ....libraries.html_document.tags.tbody import tbody
from ....libraries.html_document.tags.td import td
from ....libraries.html_document.tags.th import th
from ....libraries.html_document.tags.thead import thead
from ....libraries.html_document.tags.title import title
from ....libraries.html_document.tags.tr import tr
