
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-22T10:48:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fff8a650645c7961f3c67d7502a1082d243bff65",
 "version": "1.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
