
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-26T11:06:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc0a5e7b75c8ca0d660f7f0aea203e4ca424df9f",
 "version": "1.0.64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
