
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-22T15:45:07+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "7287ca3a3f9662b7c5f36b8ce024e27715499fa1",
 "version": "0.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
