VERSION_YEAR = 2024
VERSION_MONTH = int('02')
VERSION_DAY = int('25')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('25')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202402250725
version_date = '2024/02/25 07:25'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
