# Generated by Django 4.1.10 on 2023-09-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crx_settings_override', '0002_alter_layoutsettingsoverride_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutsettingsoverride',
            name='navbar_class',
        ),
        migrations.RemoveField(
            model_name='layoutsettingsoverride',
            name='navbar_collapse_mode',
        ),
        migrations.RemoveField(
            model_name='layoutsettingsoverride',
            name='navbar_color_scheme',
        ),
        migrations.RemoveField(
            model_name='layoutsettingsoverride',
            name='navbar_content_fluid',
        ),
        migrations.RemoveField(
            model_name='layoutsettingsoverride',
            name='navbar_fixed',
        ),
        migrations.RemoveField(
            model_name='layoutsettingsoverride',
            name='navbar_format',
        ),
        migrations.RemoveField(
            model_name='layoutsettingsoverride',
            name='navbar_search',
        ),
    ]
