# Generated by Django 4.1.13 on 2024-02-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crx_settings_override', '0004_alter_translatablenavbar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translatablefooter',
            options={'verbose_name': 'Translatable Footer', 'verbose_name_plural': 'Translatable Footers'},
        ),
    ]
