"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from ivycheck import utils
from typing import Optional


@dataclasses.dataclass
class Parameters:
    pass


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CheckConfigMinimal:
    UNSET='__SPEAKEASY_UNSET__'
    check_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('check_name') }})
    check_version: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('check_version'), 'exclude': lambda f: f is CheckConfigMinimal.UNSET }})
    parameters: Optional[Parameters] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('parameters'), 'exclude': lambda f: f is CheckConfigMinimal.UNSET }})
    

