
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-21T21:04:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ad23dea6adbb33968d8b7d3334ccc4d41c458d8",
 "version": "1.21.1.post0.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
