# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resemble/v1alpha1/errors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresemble/v1alpha1/errors.proto\x12\x11resemble.v1alpha1\"\x19\n\x17\x41\x63torAlreadyConstructed\"3\n\x13\x41\x63torNotConstructed\x12\x1c\n\x14requires_constructor\x18\x01 \x01(\x08\"\x10\n\x0eUnknownService\"\x12\n\x10PermissionDenied\"\x11\n\x0fUnauthenticated\"\r\n\x0bUnavailableb\x06proto3')



_ACTORALREADYCONSTRUCTED = DESCRIPTOR.message_types_by_name['ActorAlreadyConstructed']
_ACTORNOTCONSTRUCTED = DESCRIPTOR.message_types_by_name['ActorNotConstructed']
_UNKNOWNSERVICE = DESCRIPTOR.message_types_by_name['UnknownService']
_PERMISSIONDENIED = DESCRIPTOR.message_types_by_name['PermissionDenied']
_UNAUTHENTICATED = DESCRIPTOR.message_types_by_name['Unauthenticated']
_UNAVAILABLE = DESCRIPTOR.message_types_by_name['Unavailable']
ActorAlreadyConstructed = _reflection.GeneratedProtocolMessageType('ActorAlreadyConstructed', (_message.Message,), {
  'DESCRIPTOR' : _ACTORALREADYCONSTRUCTED,
  '__module__' : 'resemble.v1alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ActorAlreadyConstructed)
  })
_sym_db.RegisterMessage(ActorAlreadyConstructed)

ActorNotConstructed = _reflection.GeneratedProtocolMessageType('ActorNotConstructed', (_message.Message,), {
  'DESCRIPTOR' : _ACTORNOTCONSTRUCTED,
  '__module__' : 'resemble.v1alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ActorNotConstructed)
  })
_sym_db.RegisterMessage(ActorNotConstructed)

UnknownService = _reflection.GeneratedProtocolMessageType('UnknownService', (_message.Message,), {
  'DESCRIPTOR' : _UNKNOWNSERVICE,
  '__module__' : 'resemble.v1alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.UnknownService)
  })
_sym_db.RegisterMessage(UnknownService)

PermissionDenied = _reflection.GeneratedProtocolMessageType('PermissionDenied', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONDENIED,
  '__module__' : 'resemble.v1alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.PermissionDenied)
  })
_sym_db.RegisterMessage(PermissionDenied)

Unauthenticated = _reflection.GeneratedProtocolMessageType('Unauthenticated', (_message.Message,), {
  'DESCRIPTOR' : _UNAUTHENTICATED,
  '__module__' : 'resemble.v1alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.Unauthenticated)
  })
_sym_db.RegisterMessage(Unauthenticated)

Unavailable = _reflection.GeneratedProtocolMessageType('Unavailable', (_message.Message,), {
  'DESCRIPTOR' : _UNAVAILABLE,
  '__module__' : 'resemble.v1alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.Unavailable)
  })
_sym_db.RegisterMessage(Unavailable)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTORALREADYCONSTRUCTED._serialized_start=53
  _ACTORALREADYCONSTRUCTED._serialized_end=78
  _ACTORNOTCONSTRUCTED._serialized_start=80
  _ACTORNOTCONSTRUCTED._serialized_end=131
  _UNKNOWNSERVICE._serialized_start=133
  _UNKNOWNSERVICE._serialized_end=149
  _PERMISSIONDENIED._serialized_start=151
  _PERMISSIONDENIED._serialized_end=169
  _UNAUTHENTICATED._serialized_start=171
  _UNAUTHENTICATED._serialized_end=188
  _UNAVAILABLE._serialized_start=190
  _UNAVAILABLE._serialized_end=203
# @@protoc_insertion_point(module_scope)
