__license__ = '''
sodom
Copyright (C) 2023  Dmitry Protasov (inbox@protaz.ru)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, either version 3 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General
Public License along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''

from sodom.elements import NormalElement as __NormalElement
from sodom.elements import VoidElement as __VoidElement
from sodom import literals as __literals


##### NORMAL #####
a = __NormalElement[__literals.A]('a')
abbr = __NormalElement[__literals.ABBR]('abbr')
acronym = __NormalElement[__literals.ACRONYM]('acronym')
address = __NormalElement[__literals.ADDRESS]('address')
article = __NormalElement[__literals.ARTICLE]('article')
aside = __NormalElement[__literals.ASIDE]('aside')
audio = __NormalElement[__literals.AUDIO]('audio')
b = __NormalElement[__literals.B]('b')
bdi = __NormalElement[__literals.BDI]('bdi')
bdo = __NormalElement[__literals.BDO]('bdo')
big = __NormalElement[__literals.BIG]('big')
blockquote = __NormalElement[__literals.BLOCKQUOTE]('blockquote')
body = __NormalElement[__literals.BODY]('body')
button = __NormalElement[__literals.BUTTON]('button')
canvas = __NormalElement[__literals.CANVAS]('canvas')
caption = __NormalElement[__literals.CAPTION]('caption')
center = __NormalElement[__literals.CENTER]('center')
cite = __NormalElement[__literals.CITE]('cite')
code = __NormalElement[__literals.CODE]('code')
colgroup = __NormalElement[__literals.COLGROUP]('colgroup')
data = __NormalElement[__literals.DATA]('data')
datalist = __NormalElement[__literals.DATALIST]('datalist')
dd = __NormalElement[__literals.DD]('dd')
del_ = __NormalElement[__literals.DEL]('del')
details = __NormalElement[__literals.DETAILS]('details')
dfn = __NormalElement[__literals.DFN]('dfn')
dialog = __NormalElement[__literals.DIALOG]('dialog')
dir_ = __NormalElement[__literals.DIR]('dir')
div = __NormalElement[__literals.DIV]('div')
dl = __NormalElement[__literals.DL]('dl')
dt = __NormalElement[__literals.DT]('dt')
em = __NormalElement[__literals.EM]('em')
fieldset = __NormalElement[__literals.FIELDSET]('fieldset')
figcaption = __NormalElement[__literals.FIGCAPTION]('figcaption')
figure = __NormalElement[__literals.FIGURE]('figure')
font = __NormalElement[__literals.FONT]('font')
footer = __NormalElement[__literals.FOOTER]('footer')
form = __NormalElement[__literals.FORM]('form')
frame = __NormalElement[__literals.FRAME]('frame')
frameset = __NormalElement[__literals.FRAMESET]('frameset')
h1 = __NormalElement[__literals.H1]('h1')
h2 = __NormalElement[__literals.H2]('h2')
h3 = __NormalElement[__literals.H3]('h3')
h4 = __NormalElement[__literals.H4]('h4')
h5 = __NormalElement[__literals.H5]('h5')
h6 = __NormalElement[__literals.H6]('h6')
head = __NormalElement[__literals.HEAD]('head')
header = __NormalElement[__literals.HEADER]('header')
hgroup = __NormalElement[__literals.HGROUP]('hgroup')
html = __NormalElement[__literals.HTML]('html')
i = __NormalElement[__literals.I]('i')
iframe = __NormalElement[__literals.IFRAME]('iframe')
image = __NormalElement[__literals.IMAGE]('image')
ins = __NormalElement[__literals.INS]('ins')
kbd = __NormalElement[__literals.KBD]('kbd')
label = __NormalElement[__literals.LABEL]('label')
legend = __NormalElement[__literals.LEGEND]('legend')
li = __NormalElement[__literals.LI]('li')
main = __NormalElement[__literals.MAIN]('main')
map_ = __NormalElement[__literals.MAP]('map')
mark = __NormalElement[__literals.MARK]('mark')
marquee = __NormalElement[__literals.MARQUEE]('marquee')
menu = __NormalElement[__literals.MENU]('menu')
menuitem = __NormalElement[__literals.MENUITEM]('menuitem')
meter = __NormalElement[__literals.METER]('meter')
nav = __NormalElement[__literals.NAV]('nav')
nobr = __NormalElement[__literals.NOBR]('nobr')
noembed = __NormalElement[__literals.NOEMBED]('noembed')
noframes = __NormalElement[__literals.NOFRAMES]('noframes')
noscript = __NormalElement[__literals.NOSCRIPT]('noscript')
object_ = __NormalElement[__literals.OBJECT]('object')
ol = __NormalElement[__literals.OL]('ol')
optgroup = __NormalElement[__literals.OPTGROUP]('optgroup')
option = __NormalElement[__literals.OPTION]('option')
output = __NormalElement[__literals.OUTPUT]('output')
p = __NormalElement[__literals.P]('p')
picture = __NormalElement[__literals.PICTURE]('picture')
plaintext = __NormalElement[__literals.PLAINTEXT]('plaintext')
portal = __NormalElement[__literals.PORTAL]('portal')
pre = __NormalElement[__literals.PRE]('pre')
progress = __NormalElement[__literals.PROGRESS]('progress')
q = __NormalElement[__literals.Q]('q')
rb = __NormalElement[__literals.RB]('rb')
rp = __NormalElement[__literals.RP]('rp')
rt = __NormalElement[__literals.RT]('rt')
rtc = __NormalElement[__literals.RTC]('rtc')
ruby = __NormalElement[__literals.RUBY]('ruby')
s = __NormalElement[__literals.S]('s')
samp = __NormalElement[__literals.SAMP]('samp')
script = __NormalElement[__literals.SCRIPT]('script')
search = __NormalElement[__literals.SEARCH]('search')
section = __NormalElement[__literals.SECTION]('section')
select = __NormalElement[__literals.SELECT]('select')
slot = __NormalElement[__literals.SLOT]('slot')
small = __NormalElement[__literals.SMALL]('small')
span = __NormalElement[__literals.SPAN]('span')
strike = __NormalElement[__literals.STRIKE]('strike')
strong = __NormalElement[__literals.STRONG]('strong')
style = __NormalElement[__literals.STYLE]('style')
sub = __NormalElement[__literals.SUB]('sub')
summary = __NormalElement[__literals.SUMMARY]('summary')
sup = __NormalElement[__literals.SUP]('sup')
table = __NormalElement[__literals.TABLE]('table')
tbody = __NormalElement[__literals.TBODY]('tbody')
td = __NormalElement[__literals.TD]('td')
template = __NormalElement[__literals.TEMPLATE]('template')
textarea = __NormalElement[__literals.TEXTAREA]('textarea')
tfoot = __NormalElement[__literals.TFOOT]('tfoot')
th = __NormalElement[__literals.TH]('th')
thead = __NormalElement[__literals.THEAD]('thead')
time = __NormalElement[__literals.TIME]('time')
title = __NormalElement[__literals.TITLE]('title')
tr = __NormalElement[__literals.TR]('tr')
tt = __NormalElement[__literals.TT]('tt')
u = __NormalElement[__literals.U]('u')
ul = __NormalElement[__literals.UL]('ul')
var = __NormalElement[__literals.VAR]('var')
video = __NormalElement[__literals.VIDEO]('video')
xmp = __NormalElement[__literals.XMP]('xmp')


##### VOID #####
area = __VoidElement[__literals.AREA]('area')
base = __VoidElement[__literals.BASE]('base')
br = __VoidElement[__literals.BR]('br')
col = __VoidElement[__literals.COL]('col')
embed = __VoidElement[__literals.EMBED]('embed')
hr = __VoidElement[__literals.HR]('hr')
img = __VoidElement[__literals.IMG]('img')
input_ = __VoidElement[__literals.INPUT]('input')
link = __VoidElement[__literals.LINK]('link')
meta = __VoidElement[__literals.META]('meta')
param = __VoidElement[__literals.PARAM]('param')
source = __VoidElement[__literals.SOURCE]('source')
track = __VoidElement[__literals.TRACK]('track')
wbr = __VoidElement[__literals.WBR]('wbr')


##### INPUT #####
input_datetime_local = input_(type='datetime-local')
input_button = input_(type='button')
input_checkbox = input_(type='checkbox')
input_color = input_(type='color')
input_date = input_(type='date')
input_email = input_(type='email')
input_file = input_(type='file')
input_hidden = input_(type='hidden')
input_image = input_(type='image')
input_month = input_(type='month')
input_number = input_(type='number')
input_password = input_(type='password')
input_radio = input_(type='radio')
input_range = input_(type='range')
input_reset = input_(type='reset')
input_search = input_(type='search')
input_submit = input_(type='submit')
input_tel = input_(type='tel')
input_text = input_(type='text')
input_time = input_(type='time')
input_url = input_(type='url')
input_week = input_(type='week')
