
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-21T10:53:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7774313c600614579d98eea0695e1fb0603db498",
 "version": "2.30.2b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
