# Generated by Django 4.1.11 on 2023-09-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crx_settings_override", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layoutsettingsoverride",
            options={"verbose_name": "CRX Settings Overrides"},
        ),
        migrations.RemoveField(
            model_name="layoutsettingsoverride",
            name="external_new_tab",
        ),
        migrations.RemoveField(
            model_name="layoutsettingsoverride",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="layoutsettingsoverride",
            name="from_email_address",
        ),
        migrations.RemoveField(
            model_name="layoutsettingsoverride",
            name="frontend_theme",
        ),
        migrations.RemoveField(
            model_name="layoutsettingsoverride",
            name="google_maps_api_key",
        ),
        migrations.RemoveField(
            model_name="layoutsettingsoverride",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="layoutsettingsoverride",
            name="mailchimp_api_key",
        ),
        migrations.RemoveField(
            model_name="layoutsettingsoverride",
            name="search_num_results",
        ),
    ]
