# Generated by Django 4.1.13 on 2024-02-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crx_settings_override', '0003_remove_layoutsettingsoverride_navbar_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translatablenavbar',
            options={'verbose_name': 'Translatable Navigation Bar', 'verbose_name_plural': 'Translatable Navigation Bars'},
        ),
    ]
