
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-26T02:34:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0582afd58957e731444e2a43052e83eaf5cac93c",
 "version": "1.1.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
