# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Services.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Authentication_pb2 as Authentication__pb2
import BasicResponse_pb2 as BasicResponse__pb2
import ModuleConfiguration_pb2 as ModuleConfiguration__pb2
import BusConfiguration_pb2 as BusConfiguration__pb2
import Status_pb2 as Status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eServices.proto\x12\x1d\x63om.jifeline.OpenOBD.Protocol\x1a\x14\x41uthentication.proto\x1a\x13\x42\x61sicResponse.proto\x1a\x19ModuleConfiguration.proto\x1a\x16\x42usConfiguration.proto\x1a\x0cStatus.proto2\x9b\x02\n\x15\x41uthenticationService\x12{\n\x0c\x41uthenticate\x12\x34.com.jifeline.OpenOBD.Protocol.AuthenticationRequest\x1a\x35.com.jifeline.OpenOBD.Protocol.AuthenticationResponse\x12\x84\x01\n\x15RefreshAuthentication\x12\x34.com.jifeline.OpenOBD.Protocol.AuthenticationRequest\x1a\x35.com.jifeline.OpenOBD.Protocol.AuthenticationResponse2\x95\x01\n\x1aModuleConfigurationService\x12w\n\x1arequestModuleConfiguration\x12\x32.com.jifeline.OpenOBD.Protocol.ModuleConfiguration\x1a%.com.jifeline.OpenOBD.Protocol.Result2\xe7\x01\n\x11RemoteDiagnostics\x12\x66\n\x0c\x43onfigureBus\x12/.com.jifeline.OpenOBD.Protocol.BusConfiguration\x1a%.com.jifeline.OpenOBD.Protocol.Status\x12j\n\x0e\x43onfigureBuses\x12/.com.jifeline.OpenOBD.Protocol.BusConfiguration\x1a%.com.jifeline.OpenOBD.Protocol.Status(\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_AUTHENTICATIONSERVICE']._serialized_start=158
  _globals['_AUTHENTICATIONSERVICE']._serialized_end=441
  _globals['_MODULECONFIGURATIONSERVICE']._serialized_start=444
  _globals['_MODULECONFIGURATIONSERVICE']._serialized_end=593
  _globals['_REMOTEDIAGNOSTICS']._serialized_start=596
  _globals['_REMOTEDIAGNOSTICS']._serialized_end=827
# @@protoc_insertion_point(module_scope)
