'''
## This file is autogenerated from macrosynergy setup.py.

It contains version information for the macrosynergy package.

short_version: 0.1.7

version: 0.1.7

full_version: 0.1.7

git_revision: 3e26fa28d021dc18619a63e3db536c6e9632ee2c

release: True

'''
short_version: str = '0.1.7'
version: str = '0.1.7'
full_version: str = '0.1.7'
git_revision: str = '3e26fa28d021dc18619a63e3db536c6e9632ee2c'
release: bool = True
if not release:
    version = full_version
