
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-26T10:41:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ef50daee9fad76624dec7b0b5a9280117852785",
 "version": "1.8.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
