# Generated by Django 5.0.2 on 2024-02-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artd_partner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfobipCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "endpoint_url",
                    models.CharField(
                        help_text="Infobip endpoint URL",
                        max_length=255,
                        verbose_name="Endpoint URL",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Infobip API Key",
                        max_length=255,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Select the partner for which you are creating the Infobip Credential",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infobip Credential",
                "verbose_name_plural": "Infobip Credentials",
            },
        ),
    ]
