# Generated by Django 5.0.2 on 2024-02-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_infobip", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfobipSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "to",
                    models.CharField(
                        help_text="Recipient's phone number",
                        max_length=20,
                        verbose_name="To",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message to be sent", verbose_name="Message"
                    ),
                ),
                (
                    "infobip_credential",
                    models.ForeignKey(
                        help_text="Select the Infobip Credential for which you are sending the SMS",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_infobip.infobipcredential",
                        verbose_name="Infobip Credential",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infobip SMS",
                "verbose_name_plural": "Infobip SMSs",
            },
        ),
    ]
