# Generated by Django 5.0.2 on 2024-02-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_infobip", "0003_infobipsms_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="infobipsms",
            name="message_id",
            field=models.CharField(
                blank=True,
                help_text="Infobip message ID",
                max_length=255,
                null=True,
                verbose_name="Message ID",
            ),
        ),
    ]
