
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-26T14:24:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6b16a7e735869343a094a5e5d475a3eac14afe3",
 "version": "8.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
