# coding: utf-8

"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from fuse_client import schemas  # noqa: F401


class Product(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "account_details": "ACCOUNT_DETAILS",
            "balance": "BALANCE",
            "ownership": "OWNERSHIP",
            "transactions": "TRANSACTIONS",
            "investments": "INVESTMENTS",
            "assets": "ASSETS",
        }
    
    @schemas.classproperty
    def ACCOUNT_DETAILS(cls):
        return cls("account_details")
    
    @schemas.classproperty
    def BALANCE(cls):
        return cls("balance")
    
    @schemas.classproperty
    def OWNERSHIP(cls):
        return cls("ownership")
    
    @schemas.classproperty
    def TRANSACTIONS(cls):
        return cls("transactions")
    
    @schemas.classproperty
    def INVESTMENTS(cls):
        return cls("investments")
    
    @schemas.classproperty
    def ASSETS(cls):
        return cls("assets")
